
GET https://wl5j7206u2.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://wl5j7206u2.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

{
    "location": "Ottawa"
}
###

PUT https://wl5j7206u2.execute-api.us-east-1.amazonaws.com/prod/spaces?id=ef3227dd-ec11-4a40-bc89-5f340cbed064
content-type: application/json

{
    "location": "Nepean"
}
###