# .github/actions/deploy-project/action.yml
name: "Deploy project"
description: "Deploys the specified project if any of its files have changed"
inputs:
  projectName:
    description: "The name of the project to deploy"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      run: |
        echo "Setting up Node.js..."
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
      shell: bash

    - name: Install AWS CDK
      run: |
        echo "Installing AWS CDK..."
        npm install -g aws-cdk
      shell: bash

    - name: Deploy
      run: |
        echo "Deploying ${{ inputs.projectName }}..."
        cd ${{ inputs.projectName }}
        npm install
        cdk deploy --all --require-approval never
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SHORTNER_BASE_URL: ${{ secrets.SHORTNER_BASE_URL }}
        SHORTNER_TABLE_PREFIX: ${{ secrets.SHORTNER_TABLE_PREFIX }}
        SHORTNER_TABLE_NAME: ${{ secrets.SHORTNER_TABLE_NAME }}
