name: "Deploy action"
description: "Deploys the specified project if any of its files have changed"
inputs:
  projectName:
    description: "The name of the project to deploy"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Yarn
      run: npm install -g yarn@1.22.19
      shell: bash

    - name: Install AWS CDK
      run: |
        echo "Installing AWS CDK..."
        yarn global add aws-cdk
      shell: bash

    - name: Install dependencies for client
      run: |
        if [ -d "${{ inputs.projectName }}/client" ]; then
          cd "${{ inputs.projectName }}/client" && yarn install
        else
          echo "No client directory found"
        fi
      shell: bash
      working-directory: ${{ inputs.projectName }}/client

    - name: Build client
      run: |
        if [ -d "${{ inputs.projectName }}/client" ]; then
          cd "${{ inputs.projectName }}/client" && yarn build
        else
          echo "No client directory found"
        fi
      shell: bash
      working-directory: ${{ inputs.projectName }}/client

    - name: Deploy
      run: |
        echo "Deploying ${{ inputs.projectName }}..."
        cd ${{ inputs.projectName }}
        yarn install
        cdk deploy --all --require-approval never
      shell: bash
