name: Build, Lint, and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Filter changed files
        id: filter-changed-files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            url-shortner:
              - 'url-shortner/**'
              - '!url-shortner/**/*.md'
              - '!url-shortner/.gitignore'

      - name: Test URL Shortner
        if: steps.filter-changed-files.outputs.url-shortner == 'true'
        uses: ./.github/actions/test-node-app
        with:
          directory: "url-shortner"
          client-directory: "url-shortner/client"
