name: Deployment
on:
  workflow_run:
    workflows: ["Build, Lint, and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Filter changed files
        id: filter-changed-files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            aws-cdk:
              - 'aws-cdk/**'
              - '!aws-cdk/**/*.test.ts'
              - '!aws-cdk/**/*.md'

      - name: Set commit hash as env var
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Deploy aws-cdk project
        if: steps.filter-changed-files.outputs.aws-cdk == 'true'
        uses: ./.github/actions/aws-deploy
        with:
          projectName: "aws-cdk"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SHORTNER_BASE_URL: ${{ secrets.SHORTNER_BASE_URL }}
          SHORTNER_TABLE_PREFIX: ${{ secrets.SHORTNER_TABLE_PREFIX }}
          REACT_APP_ENDPOINT_API: ${{ secrets.REACT_APP_ENDPOINT_API }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
